const TOUR_STEPS = [
  {
    icon: "🎮",
    title: "1. HUD TACTIQUE & BUFFS DE COMBAT PGM",
    targetId: "hud-header",
    text: "Surveillez vos constantes en haut du HUD : <b>XP</b>, <b>Rang Apex</b>, <b>Crypto-Geom ($)</b> et <b>STREAK MULTI</b>. Enchaînez les tirs critiques sans erreur pour débloquer le loot PGM !"
  },
  {
    icon: "🗺️",
    title: "2. TREE OF CHAMPIONS : 8 RANGS & 6 MONDES AAA",
    targetId: "sidebar",
    text: "Infiltrez 6 mondes tactiques : du <b>Radar Tactique</b> aux enclos d'<b>Isla Hitbox</b> (Jurassic World) et aux donjons de <b>Sanctuary Arcane</b> (Diablo IV). Franchissez les 8 Rangs PGM pour défier le Boss."
  },
  {
    icon: "🖥️",
    title: "3. MATRICE & CANVASES D'ENGAGEMENT",
    targetId: "canvas-container",
    text: "Zone d'engagement dynamique. Effectuez vos scans radars, calibrez vos miroirs lasers ou vectorisez vos déplacements en temps réel sur la matrice interactive."
  },
  {
    icon: "📐",
    title: "4. ARMURERIE & LOADOUT TACTIQUE",
    targetId: "hud-footer",
    text: "Déployez votre <b>Lame Secrète Graduée</b>, votre <b>Katana Monomoléculaire 90°</b> ou votre <b>Compteur Vice Sunset</b>. Aimantage automatique garanti sur les hitboxes ennemies !"
  },
  {
    icon: "⌨️",
    title: "5. VERROUILLAGE TARGET & KEYPAD HOLO",
    targetId: "input-overlay",
    text: "Sélectionnez la coordonnée cible via les <b>CHOIX TACTIQUES RAPIDES (QCM)</b> ou ouvrez le <b>Keypad Holo PGM</b>. Une fois la valeur verrouillée, pressez <b>FIRING / SHOOT / ENGAGE !</b>"
  },
  {
    icon: "📁",
    title: "6. TACTICAL DATABASE & DRONE DE RECON",
    targetId: "quest-demo-btn",
    text: "Bloqué sur le terrain ? Déployez la <b>TACTICAL DATABASE / Drone de Recon</b> pour analyser les données de vol, réviser la règle géométrique et exécuter le tir parfait."
  }
];

/* ==========================================================================
SHOP_SKINS ENRICHI : VISUELS AAA & RÉFÉRENCES POP-CULTURE
========================================================================== */
const SHOP_SKINS = [
  // --- STARTERS & GRATUITS ---
  {
    id: "skin_avatar_gamer",
    type: "avatar",
    name: "Gamer Original",
    rarity: "Commune",
    price: 0,
    gameRef: "Cyberpunk",
    desc: "Insigne néon cyan rétro-éclairé de recrue PGM.",
    iconName: "gamepad-2",
    palette: ["#00f0ff", "#0077ff"],
    glowColor: "rgba(0, 240, 255, 0.6)",
    shadowBlur: "12px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-cyan-500 to-blue-700 text-cyan-200 border-cyan-400 shadow-[0_0_12px_rgba(0,240,255,0.6)]",
    config3D: {
      meshType: "gamerCoin3d",
      colorMain: "#00f0ff",
      colorGlow: "#0077ff",
      colorAccent: "#ffffff",
      roughness: 0.3,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_crosshair_classic",
    type: "crosshair",
    name: "Standard Tactical",
    rarity: "Commune",
    price: 0,
    gameRef: "CS:GO",
    desc: "Réticule vert émeraude d'alignement chirurgical.",
    color: "#00ff66",
    iconName: "crosshair",
    renderStyle: "classic",
    palette: ["#00ff66", "#008033"],
    glowColor: "rgba(0, 255, 102, 0.5)",
    shadowBlur: "8px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-600 to-green-800 text-emerald-200 border-emerald-400 shadow-[0_0_8px_rgba(0,255,102,0.5)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#00ff66",
      colorGlow: "#00ff66",
      colorAccent: "#008033",
      roughness: 0.1,
      metalness: 0.1,
      wireframe: true,
      rotationSpeed: 0.005,
      particleEffect: "none"
    }
  },
  {
    id: "skin_canvas_dark",
    type: "canvas",
    name: "Matrice Deep Space",
    rarity: "Commune",
    price: 0,
    gameRef: "Base",
    desc: "Fond de canvas nébulosité sombre bleu nuit.",
    bg: "#080d19",
    grid: "rgba(30, 45, 74, 0.4)",
    iconName: "square",
    palette: ["#080d19", "#1e2d4a"],
    glowColor: "rgba(30, 45, 74, 0.4)",
    shadowBlur: "10px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-slate-700 to-slate-900 text-slate-300 border-slate-500 shadow-[0_0_8px_rgba(30,45,74,0.4)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#080d19",
      colorGlow: "#1e2d4a",
      colorAccent: "#00f0ff",
      roughness: 0.9,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.001,
      particleEffect: "none"
    }
  },

  // --- THÈMES COLORIMÉTRIQUES XP ---
  {
    id: "skin_xp_theme_cyber_cyan",
    type: "xp_theme",
    name: "Cyber Cyan & Émeraude",
    rarity: "Commune",
    price: 0,
    gameRef: "Cyberpunk 2077",
    desc: "Dégradé néon cyan vers vert émeraude avec impulsion lumineuse.",
    cssClass: "xp-theme-cyber-cyan",
    iconName: "zap",
    palette: ["#00f0ff", "#00ff66"],
    glowColor: "rgba(0, 240, 255, 0.7)",
    shadowBlur: "12px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-cyan-600 to-emerald-600 text-cyan-100 border-cyan-400 shadow-[0_0_10px_rgba(0,240,255,0.5)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#00f0ff",
      colorGlow: "#00ff66",
      colorAccent: "#ffffff",
      roughness: 0.2,
      metalness: 0.5,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_xp_theme_solar_gold",
    type: "xp_theme",
    name: "Flamme Solaire Gold",
    rarity: "Rare",
    price: 250,
    gameRef: "Elden Ring",
    desc: "Énergie aurique incandescente ambre et or pur.",
    cssClass: "xp-theme-solar-gold",
    iconName: "flame",
    palette: ["#fbbf24", "#d97706"],
    glowColor: "rgba(251, 191, 36, 0.8)",
    shadowBlur: "15px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-500 to-yellow-700 text-amber-100 border-yellow-300 shadow-[0_0_12px_rgba(251,191,36,0.6)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#fbbf24",
      colorGlow: "#d97706",
      colorAccent: "#ffffff",
      roughness: 0.1,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.02,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_xp_theme_synthwave_fuchsia",
    type: "xp_theme",
    name: "Néon Synthwave Fuchsia",
    rarity: "Rare",
    price: 300,
    gameRef: "GTA Vice City",
    desc: "Dégradé fuchsia vibrant, violet et orange sunset 80s.",
    cssClass: "xp-theme-synthwave-fuchsia",
    iconName: "sun",
    palette: ["#e11d48", "#c084fc", "#f97316"],
    glowColor: "rgba(225, 29, 72, 0.8)",
    shadowBlur: "16px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-fuchsia-600 to-pink-700 text-pink-100 border-pink-400 shadow-[0_0_14px_rgba(236,72,153,0.6)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#e11d48",
      colorGlow: "#c084fc",
      colorAccent: "#f97316",
      roughness: 0.3,
      metalness: 0.7,
      wireframe: true,
      rotationSpeed: 0.018,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_xp_theme_matrix_emerald",
    type: "xp_theme",
    name: "Matrix Emerald Code",
    rarity: "Épique",
    price: 600,
    gameRef: "Matrix",
    desc: "Flux numérique émeraude avec balayage phosphorescent.",
    cssClass: "xp-theme-matrix-emerald",
    iconName: "binary",
    palette: ["#00ff41", "#003b00"],
    glowColor: "rgba(0, 255, 65, 0.85)",
    shadowBlur: "18px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-green-600 to-emerald-900 text-green-200 border-green-400 shadow-[0_0_16px_rgba(0,255,65,0.7)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#00ff41",
      colorGlow: "#00ff41",
      colorAccent: "#003b00",
      roughness: 0.4,
      metalness: 0.2,
      wireframe: true,
      rotationSpeed: 0.022,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_xp_theme_plasma_red",
    type: "xp_theme",
    name: "Plasma Rouge Lilith",
    rarity: "Épique",
    price: 650,
    gameRef: "Diablo IV",
    desc: "Rouge sang démoniaque et arcs de plasma rutilants.",
    cssClass: "xp-theme-plasma-red",
    iconName: "shield-alert",
    palette: ["#dc2626", "#450a0a"],
    glowColor: "rgba(220, 38, 38, 0.9)",
    shadowBlur: "20px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-red-700 to-red-950 text-red-200 border-red-500 shadow-[0_0_18px_rgba(220,38,38,0.8)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#dc2626",
      colorGlow: "#450a0a",
      colorAccent: "#ff4d4d",
      roughness: 0.2,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.025,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_xp_theme_void_purple",
    type: "xp_theme",
    name: "Surcharge Abyssale Void",
    rarity: "Légendaire",
    price: 1400,
    gameRef: "Destiny 2",
    desc: "Énergie du vide instable pulsating entre violet obscur et magenta éthéré.",
    cssClass: "xp-theme-void-purple",
    iconName: "sparkles",
    palette: ["#a855f7", "#3b0764", "#ec4899"],
    glowColor: "rgba(168, 85, 247, 0.95)",
    shadowBlur: "24px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-purple-600 via-fuchsia-700 to-slate-950 text-purple-200 border-purple-400 shadow-[0_0_22px_rgba(168,85,247,0.85)]",
    config3D: {
      meshType: "xpOrb3d",
      colorMain: "#a855f7",
      colorGlow: "#ec4899",
      colorAccent: "#3b0764",
      roughness: 0.1,
      metalness: 0.9,
      wireframe: true,
      rotationSpeed: 0.03,
      particleEffect: "floatingRings"
    }
  },

  // --- AVATARS POP-CULTURE ---
  {
    id: "skin_avatar_steve_block",
    type: "avatar",
    name: "Voxel Master",
    rarity: "Rare",
    price: 200,
    gameRef: "Minecraft",
    desc: "Cadre cubique pixelisé vert Herbe & Obsidienne.",
    iconName: "box",
    palette: ["#10b981", "#78350f"],
    glowColor: "rgba(16, 185, 129, 0.5)",
    shadowBlur: "12px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-700 via-green-600 to-amber-800 text-green-200 border-emerald-400 shadow-[0_0_12px_rgba(16,185,129,0.5)]",
    config3D: {
      meshType: "voxelMaster3d",
      colorMain: "#10b981",
      colorGlow: "#10b981",
      colorAccent: "#78350f",
      roughness: 0.8,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "none"
    }
  },
  {
    id: "skin_avatar_dead_slayer",
    type: "avatar",
    name: "Slayer Zombie Mask",
    rarity: "Rare",
    price: 280,
    gameRef: "Dead Island 2",
    desc: "Masque de massacreur d'HELL-A aux yeux phosphorescents.",
    iconName: "skull",
    palette: ["#e11d48", "#18181b"],
    glowColor: "rgba(225, 29, 72, 0.6)",
    shadowBlur: "15px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-red-900 via-zinc-900 to-rose-700 text-red-400 border-red-500 shadow-[0_0_15px_rgba(225,29,72,0.6)]",
    config3D: {
      meshType: "slayerSkull3d",
      colorMain: "#e11d48",
      colorGlow: "#e11d48",
      colorAccent: "#18181b",
      roughness: 0.6,
      metalness: 0.4,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_motorfest_rider",
    type: "avatar",
    name: "Casque Apex Nitro",
    rarity: "Rare",
    price: 320,
    gameRef: "Motorfest",
    desc: "Fibre de carbone mat avec reflet de visière irisé.",
    iconName: "gauge",
    palette: ["#f97316", "#0f172a"],
    glowColor: "rgba(249, 115, 22, 0.6)",
    shadowBlur: "15px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-slate-900 via-orange-600 to-red-600 text-orange-200 border-orange-500 shadow-[0_0_15px_rgba(249,115,22,0.6)]",
    config3D: {
      meshType: "motorfestHelmet3d",
      colorMain: "#f97316",
      colorGlow: "#f97316",
      colorAccent: "#0f172a",
      roughness: 0.3,
      metalness: 0.7,
      wireframe: false,
      rotationSpeed: 0.012,
      particleEffect: "none"
    }
  },
  {
    id: "skin_avatar_raptor_tactical",
    type: "avatar",
    name: "InGen Raptor Recon",
    rarity: "Rare",
    price: 350,
    gameRef: "Jurassic World",
    desc: "Insigne camouflage préhistorique et visière infrarouge.",
    iconName: "eye",
    palette: ["#10b981", "#14532d"],
    glowColor: "rgba(16, 185, 129, 0.6)",
    shadowBlur: "15px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-900 via-green-800 to-teal-500 text-emerald-200 border-emerald-400 shadow-[0_0_15px_rgba(16,185,129,0.6)]",
    config3D: {
      meshType: "raptorVisor3d",
      colorMain: "#10b981",
      colorGlow: "#10b981",
      colorAccent: "#14532d",
      roughness: 0.5,
      metalness: 0.6,
      wireframe: true,
      rotationSpeed: 0.01,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_avatar_chief_helmet",
    type: "avatar",
    name: "SPARTAN-117",
    rarity: "Épique",
    price: 500,
    gameRef: "Halo",
    desc: "Insigne vert olive militaire avec visière plasma dorée.",
    iconName: "shield",
    palette: ["#65a30d", "#d97706"],
    glowColor: "rgba(163, 230, 53, 0.5)",
    shadowBlur: "15px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-lime-800 via-emerald-900 to-amber-600 text-amber-300 border-lime-400 shadow-[0_0_15px_rgba(163,230,53,0.5)]",
    config3D: {
      meshType: "spartanHelmet3d",
      colorMain: "#65a30d",
      colorGlow: "#d97706",
      colorAccent: "#a3e635",
      roughness: 0.4,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.012,
      particleEffect: "none"
    }
  },
  {
    id: "skin_avatar_cyber_v",
    type: "avatar",
    name: "Mercenaire Night City",
    rarity: "Épique",
    price: 550,
    gameRef: "Cyberpunk 2077",
    desc: "Contour néon jaune haute tension et optiques HUD.",
    iconName: "zap",
    palette: ["#facc15", "#dc2626"],
    glowColor: "rgba(250, 204, 21, 0.7)",
    shadowBlur: "15px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-yellow-400 via-amber-500 to-red-600 text-black border-yellow-300 font-black shadow-[0_0_15px_rgba(250,204,21,0.7)]",
    config3D: {
      meshType: "cyberShield3d",
      colorMain: "#facc15",
      colorGlow: "#dc2626",
      colorAccent: "#00f0ff",
      roughness: 0.2,
      metalness: 0.9,
      wireframe: true,
      rotationSpeed: 0.02,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_apex_champion",
    type: "avatar",
    name: "Badge Apex Champion",
    rarity: "Épique",
    price: 600,
    gameRef: "Apex Legends",
    desc: "Insigne holographique réservé à la légende de l'arène.",
    iconName: "award",
    palette: ["#ef4444", "#f59e0b"],
    glowColor: "rgba(239, 68, 68, 0.7)",
    shadowBlur: "15px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-red-600 via-amber-600 to-yellow-400 text-white border-amber-300 shadow-[0_0_15px_rgba(239,68,68,0.7)]",
    config3D: {
      meshType: "apexBadge3d",
      colorMain: "#ef4444",
      colorGlow: "#f59e0b",
      colorAccent: "#ffffff",
      roughness: 0.2,
      metalness: 0.85,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_fut_champ",
    type: "avatar",
    name: "Carte EA FUT Champion",
    rarity: "Épique",
    price: 650,
    gameRef: "EA FC",
    desc: "Carte Or étincelante +99 PACE avec aura de victoire.",
    iconName: "trophy",
    palette: ["#fbbf24", "#78350f"],
    glowColor: "rgba(251, 191, 36, 0.8)",
    shadowBlur: "18px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-300 via-yellow-500 to-amber-700 text-amber-950 border-amber-200 font-extrabold shadow-[0_0_18px_rgba(251,191,36,0.8)]",
    config3D: {
      meshType: "futCard3d",
      colorMain: "#fbbf24",
      colorGlow: "#fbbf24",
      colorAccent: "#78350f",
      roughness: 0.15,
      metalness: 0.95,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_spidey_venom",
    type: "avatar",
    name: "Masque Bio-Shock",
    rarity: "Épique",
    price: 700,
    gameRef: "Spider-Man",
    desc: "Cadre rouge toile & arcs de bio-électricité jaune néon.",
    iconName: "shield-alert",
    palette: ["#ef4444", "#eab308"],
    glowColor: "rgba(239, 68, 68, 0.7)",
    shadowBlur: "15px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-red-600 via-rose-700 to-yellow-400 text-yellow-300 border-red-400 shadow-[0_0_15px_rgba(239,68,68,0.7)]",
    config3D: {
      meshType: "spideyMask3d",
      colorMain: "#ef4444",
      colorGlow: "#eab308",
      colorAccent: "#111827",
      roughness: 0.3,
      metalness: 0.5,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_gta_vice",
    type: "avatar",
    name: "Vice Sunset Legend",
    rarity: "Légendaire",
    price: 1200,
    gameRef: "GTA VI",
    desc: "Insigne Synthwave dégradé fuchsia, violet et orange sunset.",
    iconName: "sun",
    palette: ["#c084fc", "#f97316", "#ec4899"],
    glowColor: "rgba(236, 72, 153, 0.8)",
    shadowBlur: "20px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-fuchsia-600 via-pink-500 to-orange-400 text-white border-pink-300 shadow-[0_0_20px_rgba(236,72,153,0.8)]",
    config3D: {
      meshType: "viceBadge3d",
      colorMain: "#c084fc",
      colorGlow: "#ec4899",
      colorAccent: "#f97316",
      roughness: 0.2,
      metalness: 0.7,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_avatar_diablo_lilith",
    type: "avatar",
    name: "Cornes de Sanctuarium",
    rarity: "Légendaire",
    price: 1350,
    gameRef: "Diablo IV",
    desc: "Aura d'éther rouge sang et runes incandescentes.",
    iconName: "flame",
    palette: ["#dc2626", "#000000"],
    glowColor: "rgba(220, 38, 38, 0.9)",
    shadowBlur: "20px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-red-950 via-red-800 to-black text-red-400 border-red-600 shadow-[0_0_20px_rgba(220,38,38,0.9)]",
    config3D: {
      meshType: "lilithHorns3d",
      colorMain: "#dc2626",
      colorGlow: "#dc2626",
      colorAccent: "#000000",
      roughness: 0.4,
      metalness: 0.3,
      wireframe: false,
      rotationSpeed: 0.012,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_kratos_omega",
    type: "avatar",
    name: "Rune Oméga Spartan",
    rarity: "Légendaire",
    price: 1350,
    gameRef: "God of War",
    desc: "Tatouage de guerre écarlate et acier de Midgard gravé.",
    iconName: "swords",
    palette: ["#dc2626", "#e2e8f0"],
    glowColor: "rgba(220, 38, 38, 0.85)",
    shadowBlur: "22px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-red-800 via-slate-700 to-red-950 text-red-100 border-red-400 shadow-[0_0_20px_rgba(220,38,38,0.8)]",
    config3D: {
      meshType: "omegaRune3d",
      colorMain: "#dc2626",
      colorGlow: "#dc2626",
      colorAccent: "#e2e8f0",
      roughness: 0.6,
      metalness: 0.7,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_triforce_hero",
    type: "avatar",
    name: "Héros du Temps",
    rarity: "Exotique",
    price: 2500,
    gameRef: "Zelda BotW",
    desc: "Emblème sacrée de la Triforce d'or étincelante.",
    iconName: "triangle",
    palette: ["#eab308", "#059669"],
    glowColor: "rgba(234, 179, 8, 0.9)",
    shadowBlur: "22px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-200 via-yellow-400 to-emerald-600 text-amber-950 border-yellow-200 shadow-[0_0_22px_rgba(234,179,8,0.9)]",
    config3D: {
      meshType: "triforce3d",
      colorMain: "#eab308",
      colorGlow: "#eab308",
      colorAccent: "#059669",
      roughness: 0.1,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_avatar_doom_slayer",
    type: "avatar",
    name: "Praetor Suit Mark VI",
    rarity: "Exotique",
    price: 3000,
    gameRef: "DOOM Eternal",
    desc: "Armure du Doom Slayer forgée dans l'enfer d'Argent D'Nur.",
    iconName: "shield-alert",
    palette: ["#84cc16", "#b91c1c", "#15803d"],
    glowColor: "rgba(132, 204, 22, 0.95)",
    shadowBlur: "28px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-lime-600 via-red-800 to-zinc-950 text-lime-200 border-lime-400 shadow-[0_0_25px_rgba(132,204,22,0.9)]",
    config3D: {
      meshType: "praetorSuit3d",
      colorMain: "#84cc16",
      colorGlow: "#84cc16",
      colorAccent: "#b91c1c",
      roughness: 0.5,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },

  // --- VISEURS & SCOPES LASER ---
  {
    id: "skin_crosshair_classic",
    type: "crosshair",
    name: "Standard Tactical",
    rarity: "Commune",
    price: 0,
    gameRef: "CS:GO",
    desc: "Réticule vert émeraude d'alignement chirurgical.",
    color: "#00ff66",
    iconName: "crosshair",
    renderStyle: "classic",
    palette: ["#00ff66", "#008033"],
    glowColor: "rgba(0, 255, 102, 0.5)",
    shadowBlur: "8px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-600 to-green-800 text-emerald-200 border-emerald-400 shadow-[0_0_8px_rgba(0,255,102,0.5)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#00ff66",
      colorGlow: "#00ff66",
      colorAccent: "#008033",
      roughness: 0.1,
      metalness: 0.1,
      wireframe: true,
      rotationSpeed: 0.005,
      particleEffect: "none"
    }
  },
  {
    id: "skin_crosshair_red_dot",
    type: "crosshair",
    name: "Red Dot Scope",
    rarity: "Commune",
    price: 50,
    gameRef: "Call of Duty",
    desc: "Viseur point rouge laser ultra-précis.",
    color: "#ff0000",
    iconName: "dot",
    renderStyle: "classic",
    palette: ["#ff0000", "#990000"],
    glowColor: "rgba(255, 0, 0, 0.7)",
    shadowBlur: "10px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-red-600 to-rose-900 text-red-200 border-red-400 shadow-[0_0_10px_rgba(255,0,0,0.5)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#ff0000",
      colorGlow: "#ff0000",
      colorAccent: "#990000",
      roughness: 0.1,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.005,
      particleEffect: "none"
    }
  },
  {
    id: "skin_crosshair_halo_plasma",
    type: "crosshair",
    name: "Réticule Plasma Covenant",
    rarity: "Rare",
    price: 220,
    gameRef: "Halo",
    desc: "Viseur circulaire à pulsation plasma bleu aliénigène.",
    color: "#00d0ff",
    iconName: "circle-dot",
    renderStyle: "classic",
    palette: ["#00d0ff", "#0055ff"],
    glowColor: "rgba(0, 208, 255, 0.75)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-cyan-600 to-blue-800 text-cyan-100 border-cyan-300 shadow-[0_0_12px_rgba(0,208,255,0.6)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#00d0ff",
      colorGlow: "#0055ff",
      colorAccent: "#0055ff",
      roughness: 0.1,
      metalness: 0.2,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_crosshair_valorant_phantom",
    type: "crosshair",
    name: "Viseur Radiante Prime",
    rarity: "Rare",
    price: 250,
    gameRef: "Valorant",
    desc: "Réticule minimaliste violet & néon or favorisant les tirs tête.",
    color: "#c084fc",
    iconName: "crosshair",
    renderStyle: "classic",
    palette: ["#c084fc", "#fbbf24"],
    glowColor: "rgba(192, 132, 252, 0.8)",
    shadowBlur: "15px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-purple-600 to-amber-500 text-purple-100 border-purple-300 shadow-[0_0_12px_rgba(192,132,252,0.7)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#c084fc",
      colorGlow: "#c084fc",
      colorAccent: "#fbbf24",
      roughness: 0.2,
      metalness: 0.4,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_crosshair_dino_tracker",
    type: "crosshair",
    name: "Optique Thermique InGen",
    rarity: "Rare",
    price: 280,
    gameRef: "Jurassic World",
    desc: "Grille de détection infrarouge à balayage sonar.",
    color: "#00ff66",
    iconName: "scan",
    renderStyle: "dino_tracker",
    palette: ["#00ff66", "#052e16"],
    glowColor: "rgba(0, 255, 102, 0.7)",
    shadowBlur: "14px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-600 to-teal-900 text-emerald-100 border-emerald-400 shadow-[0_0_12px_rgba(0,255,102,0.6)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#00ff66",
      colorGlow: "#00ff66",
      colorAccent: "#052e16",
      roughness: 0.4,
      metalness: 0.2,
      wireframe: false,
      rotationSpeed: 0.005,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_crosshair_spider_sense",
    type: "crosshair",
    name: "Spider-Sense Reticle",
    rarity: "Épique",
    price: 500,
    gameRef: "Spider-Man",
    desc: "Ondes d'avertissement radiales bio-électriques.",
    color: "#ff0055",
    iconName: "radio",
    renderStyle: "spider_sense",
    palette: ["#ff0055", "#ffcc00"],
    glowColor: "rgba(255, 0, 85, 0.8)",
    shadowBlur: "16px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-rose-600 to-amber-500 text-rose-100 border-rose-300 shadow-[0_0_14px_rgba(255,0,85,0.7)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#ff0055",
      colorGlow: "#ff0055",
      colorAccent: "#ffcc00",
      roughness: 0.2,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_crosshair_matrix_code",
    type: "crosshair",
    name: "Réticule Matrix Code",
    rarity: "Épique",
    price: 600,
    gameRef: "Matrix",
    desc: "Viseur digital affichant le flux de code binaire Matrix.",
    color: "#00ff41",
    iconName: "binary",
    renderStyle: "classic",
    palette: ["#00ff41", "#008020"],
    glowColor: "rgba(0, 255, 65, 0.85)",
    shadowBlur: "18px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-green-500 to-emerald-900 text-green-100 border-green-300 shadow-[0_0_16px_rgba(0,255,65,0.75)]",
    config3D: {
      meshType: "reticleHolo3d",
      colorMain: "#00ff41",
      colorGlow: "#00ff41",
      colorAccent: "#008020",
      roughness: 0.3,
      metalness: 0.1,
      wireframe: true,
      rotationSpeed: 0.012,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_crosshair_diablo_hell",
    type: "crosshair",
    name: "Rune Arcane de Lilith",
    rarity: "Légendaire",
    price: 1300,
    gameRef: "Diablo IV",
    desc: "Pentagramme d'éther pulsant et cercles de ciblage démoniaque.",
    color: "#ff0033",
    iconName: "disc",
    renderStyle: "diablo_rune",
    palette: ["#ff0033", "#4a0000"],
    glowColor: "rgba(255, 0, 51, 0.9)",
    shadowBlur: "22px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-red-600 via-rose-900 to-black text-red-100 border-red-500 shadow-[0_0_20px_rgba(255,0,51,0.85)]",
    config3D: {
      meshType: "runeCircle3d",
      colorMain: "#ff0033",
      colorGlow: "#ff0033",
      colorAccent: "#4a0000",
      roughness: 0.2,
      metalness: 0.5,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_crosshair_awp_dragon",
    type: "crosshair",
    name: "AWP Dragon Lore Scope",
    rarity: "Légendaire",
    price: 1500,
    gameRef: "CS:GO / CS2",
    desc: "Optique de sniper d'or aux finitions de gravures mythiques.",
    color: "#ffd700",
    iconName: "target",
    renderStyle: "dragon_lore",
    palette: ["#ffd700", "#d97706"],
    glowColor: "rgba(255, 215, 0, 0.9)",
    shadowBlur: "24px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-400 via-yellow-600 to-amber-900 text-amber-950 border-yellow-200 shadow-[0_0_22px_rgba(255,215,0,0.85)]",
    config3D: {
      meshType: "dragonScope3d",
      colorMain: "#ffd700",
      colorGlow: "#ffd700",
      colorAccent: "#d97706",
      roughness: 0.1,
      metalness: 0.95,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_crosshair_god_eye",
    type: "crosshair",
    name: "Œil de la Grâce Céleste",
    rarity: "Exotique",
    price: 2800,
    gameRef: "Elden Ring",
    desc: "Réticule en rune d'or rayonnante pour une précision absolue.",
    color: "#fbbf24",
    iconName: "eye",
    renderStyle: "dragon_lore",
    palette: ["#fbbf24", "#fffbeb", "#b45309"],
    glowColor: "rgba(251, 191, 36, 0.85)",
    shadowBlur: "30px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-200 via-yellow-400 to-amber-600 text-amber-950 border-amber-100 shadow-[0_0_28px_rgba(251,191,36,0.95)]",
    config3D: {
      meshType: "godEye3d",
      colorMain: "#fbbf24",
      colorGlow: "#fffbeb",
      colorAccent: "#b45309",
      roughness: 0.05,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },

  // --- RÈGLES TACTIQUES ---
  {
    id: "skin_ruler_cyber",
    type: "ruler",
    name: "Règle Cyber Neon",
    rarity: "Commune",
    price: 50,
    gameRef: "Cyberpunk 2077",
    desc: "Règle graduée cyan à néon haute intensité.",
    color: "#00f0ff",
    bg: "rgba(0, 240, 255, 0.2)",
    iconName: "ruler",
    renderStyle: "cyber_ruler",
    palette: ["#00f0ff", "#0088cc"],
    glowColor: "rgba(0, 240, 255, 0.6)",
    shadowBlur: "10px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-cyan-600 to-blue-800 text-cyan-100 border-cyan-400 shadow-[0_0_10px_rgba(0,240,255,0.5)]",
    config3D: {
      meshType: "laserRuler3d",
      colorMain: "#00f0ff",
      colorGlow: "#00f0ff",
      colorAccent: "#0088cc",
      roughness: 0.2,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.005,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_ruler_quantum_beam",
    type: "ruler",
    name: "Règle Faisceau Quantique",
    rarity: "Rare",
    price: 220,
    gameRef: "Portal 2",
    desc: "Règle de précision avec flux d'énergie quantique bleue/orange.",
    color: "#ff9900",
    bg: "rgba(255, 153, 0, 0.2)",
    iconName: "zap",
    renderStyle: "quantum_beam",
    palette: ["#ff9900", "#00aaff"],
    glowColor: "rgba(255, 153, 0, 0.75)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-orange-500 to-sky-600 text-orange-100 border-orange-300 shadow-[0_0_12px_rgba(255,153,0,0.65)]",
    config3D: {
      meshType: "quantumRuler3d",
      colorMain: "#ff9900",
      colorGlow: "#ff9900",
      colorAccent: "#00aaff",
      roughness: 0.15,
      metalness: 0.7,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_ruler_motorfest_tach",
    type: "ruler",
    name: "Bande Dragstrip Nitro",
    rarity: "Rare",
    price: 280,
    gameRef: "Motorfest",
    desc: "Règle façon ligne de départ avec compte-tours et damier.",
    color: "#ff9900",
    bg: "rgba(255, 153, 0, 0.2)",
    iconName: "flag",
    renderStyle: "dragstrip",
    palette: ["#ff9900", "#18181b"],
    glowColor: "rgba(255, 153, 0, 0.7)",
    shadowBlur: "12px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-amber-600 via-zinc-800 to-orange-600 text-amber-200 border-amber-400 shadow-[0_0_12px_rgba(255,153,0,0.6)]",
    config3D: {
      meshType: "dragstripRuler3d",
      colorMain: "#ff9900",
      colorGlow: "#ff9900",
      colorAccent: "#18181b",
      roughness: 0.3,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.005,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_ruler_assassin_hidden",
    type: "ruler",
    name: "Lame Secrète Graduée",
    rarity: "Épique",
    price: 550,
    gameRef: "Assassin's Creed",
    desc: "Acier damassé gravé du symbole de la Confrérie et graduations laser.",
    color: "#00f0ff",
    bg: "rgba(0, 240, 255, 0.25)",
    iconName: "sword",
    renderStyle: "assassin_blade",
    palette: ["#00f0ff", "#94a3b8"],
    glowColor: "rgba(0, 240, 255, 0.8)",
    shadowBlur: "18px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-slate-700 via-cyan-700 to-slate-900 text-cyan-200 border-cyan-400 shadow-[0_0_16px_rgba(0,240,255,0.7)]",
    config3D: {
      meshType: "hiddenBlade3d",
      colorMain: "#00f0ff",
      colorGlow: "#00f0ff",
      colorAccent: "#94a3b8",
      roughness: 0.05,
      metalness: 0.95,
      wireframe: false,
      rotationSpeed: 0.006,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_ruler_hyperion_plasma",
    type: "ruler",
    name: "Règle Hyperion Railgun",
    rarity: "Légendaire",
    price: 1100,
    gameRef: "Borderlands",
    desc: "Règle hyper-technologique avec faisceau plasmique chaud.",
    color: "#ff5500",
    bg: "rgba(255, 85, 0, 0.25)",
    iconName: "cpu",
    renderStyle: "railgun",
    palette: ["#ff5500", "#facc15"],
    glowColor: "rgba(255, 85, 0, 0.85)",
    shadowBlur: "20px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-orange-600 via-yellow-500 to-red-700 text-yellow-100 border-yellow-300 shadow-[0_0_18px_rgba(255,85,0,0.75)]",
    config3D: {
      meshType: "railgunRuler3d",
      colorMain: "#ff5500",
      colorGlow: "#ff5500",
      colorAccent: "#facc15",
      roughness: 0.25,
      metalness: 0.85,
      wireframe: true,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_ruler_lightsaber_plasma",
    type: "ruler",
    name: "Sabre Laser Gradué",
    rarity: "Exotique",
    price: 2400,
    gameRef: "Star Wars Jedi",
    desc: "Lame de plasma pur bleu kyber émettant des étincelles sur la matrice.",
    color: "#38bdf8",
    bg: "rgba(56, 189, 248, 0.3)",
    iconName: "sword",
    renderStyle: "lightsaber",
    palette: ["#38bdf8", "#ffffff", "#0284c7"],
    glowColor: "rgba(56, 189, 248, 0.95)",
    shadowBlur: "28px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-sky-400 via-blue-600 to-cyan-200 text-sky-950 border-white shadow-[0_0_26px_rgba(56,189,248,0.9)]",
    config3D: {
      meshType: "lightsaberRuler3d",
      colorMain: "#38bdf8",
      colorGlow: "#38bdf8",
      colorAccent: "#ffffff",
      roughness: 0.05,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "sparks"
    }
  },

  // --- ÉQUERRES LASER ---
  {
    id: "skin_square_basic_laser",
    type: "square",
    name: "Équerre Néon Cyan",
    rarity: "Commune",
    price: 50,
    gameRef: "Tron",
    desc: "Équerre en fibre néon bleutée pour tracés d'angles droits.",
    color: "#00f0ff",
    bg: "rgba(0, 240, 255, 0.15)",
    iconName: "triangle",
    renderStyle: "basic_laser",
    palette: ["#00f0ff", "#0055aa"],
    glowColor: "rgba(0, 240, 255, 0.6)",
    shadowBlur: "10px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-cyan-700 to-blue-900 text-cyan-200 border-cyan-400 shadow-[0_0_10px_rgba(0,240,255,0.5)]",
    config3D: {
      meshType: "neonSquare3d",
      colorMain: "#00f0ff",
      colorGlow: "#00f0ff",
      colorAccent: "#0055aa",
      roughness: 0.2,
      metalness: 0.8,
      wireframe: true,
      rotationSpeed: 0.005,
      particleEffect: "none"
    }
  },
  {
    id: "skin_square_excalibur_laser",
    type: "square",
    name: "Équerre Excalibur Laser",
    rarity: "Rare",
    price: 240,
    gameRef: "Zelda",
    desc: "Équerre luminescente d'or et d'émeraude sacrée.",
    color: "#ffe600",
    bg: "rgba(255, 230, 0, 0.2)",
    iconName: "sparkles",
    renderStyle: "excalibur",
    palette: ["#ffe600", "#10b981"],
    glowColor: "rgba(255, 230, 0, 0.75)",
    shadowBlur: "14px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-yellow-500 via-emerald-600 to-amber-700 text-yellow-100 border-yellow-300 shadow-[0_0_12px_rgba(255,230,0,0.6)]",
    config3D: {
      meshType: "excaliburSquare3d",
      colorMain: "#ffe600",
      colorGlow: "#ffe600",
      colorAccent: "#10b981",
      roughness: 0.1,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_square_minecraft_redstone",
    type: "square",
    name: "Équerre Redstone Laser",
    rarity: "Rare",
    price: 280,
    gameRef: "Minecraft",
    desc: "Structure en blocs de Redstone traversée par un flux d'énergie.",
    color: "#ff2200",
    bg: "rgba(255, 34, 0, 0.25)",
    iconName: "box",
    renderStyle: "redstone_block",
    palette: ["#ff2200", "#990000"],
    glowColor: "rgba(255, 34, 0, 0.75)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-red-600 to-stone-900 text-red-200 border-red-400 shadow-[0_0_12px_rgba(255,34,0,0.65)]",
    config3D: {
      meshType: "redstoneSquare3d",
      colorMain: "#ff2200",
      colorGlow: "#ff2200",
      colorAccent: "#990000",
      roughness: 0.8,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.005,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_square_cyber_katana",
    type: "square",
    name: "Katana Monomoléculaire 90°",
    rarity: "Épique",
    price: 600,
    gameRef: "Cyberpunk 2077",
    desc: "Lame néon fuchsia formant un angle droit ultra-tranchant.",
    color: "#ff0055",
    bg: "rgba(255, 0, 85, 0.2)",
    iconName: "slash",
    renderStyle: "cyber_katana",
    palette: ["#ff0055", "#80002a"],
    glowColor: "rgba(255, 0, 85, 0.85)",
    shadowBlur: "18px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-rose-600 via-pink-700 to-slate-900 text-pink-100 border-pink-400 shadow-[0_0_16px_rgba(255,0,85,0.75)]",
    config3D: {
      meshType: "katana3d",
      colorMain: "#ff0055",
      colorGlow: "#ff0055",
      colorAccent: "#80002a",
      roughness: 0.15,
      metalness: 0.95,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_square_void_arc",
    type: "square",
    name: "Équerre Void Arc",
    rarity: "Légendaire",
    price: 1300,
    gameRef: "Destiny 2",
    desc: "Équerre cosmique taillée dans l'énergie abyssale violette.",
    color: "#a855f7",
    bg: "rgba(168, 85, 247, 0.25)",
    iconName: "triangle",
    renderStyle: "void_arc",
    palette: ["#a855f7", "#581c87"],
    glowColor: "rgba(168, 85, 247, 0.9)",
    shadowBlur: "22px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-purple-600 via-indigo-800 to-black text-purple-200 border-purple-400 shadow-[0_0_20px_rgba(168,85,247,0.8)]",
    config3D: {
      meshType: "voidArcSquare3d",
      colorMain: "#a855f7",
      colorGlow: "#a855f7",
      colorAccent: "#581c87",
      roughness: 0.2,
      metalness: 0.8,
      wireframe: true,
      rotationSpeed: 0.012,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_square_frostmourne_ice",
    type: "square",
    name: "Équerre Deuil-Givre",
    rarity: "Exotique",
    price: 2600,
    gameRef: "World of Warcraft",
    desc: "Glace éternelle émanant un souffle glacial à 90 degrés.",
    color: "#38bdf8",
    bg: "rgba(56, 189, 248, 0.25)",
    iconName: "snowflake",
    renderStyle: "frostmourne",
    palette: ["#38bdf8", "#e0f2fe", "#0f172a"],
    glowColor: "rgba(56, 189, 248, 0.85)",
    shadowBlur: "30px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-sky-300 via-blue-700 to-slate-950 text-sky-100 border-sky-200 shadow-[0_0_28px_rgba(56,189,248,0.95)]",
    config3D: {
      meshType: "iceSquare3d",
      colorMain: "#38bdf8",
      colorGlow: "#38bdf8",
      colorAccent: "#e0f2fe",
      roughness: 0.05,
      metalness: 0.3,
      wireframe: false,
      rotationSpeed: 0.007,
      particleEffect: "sparks"
    }
  },

  // --- RAPPORTEURS HOLO ---
  {
    id: "skin_protractor_classic_neon",
    type: "protractor",
    name: "Rapporteur Amber Grid",
    rarity: "Commune",
    price: 50,
    gameRef: "Retro Arcade",
    desc: "Rapporteur angulaire rétro-éclairé couleur ambre.",
    color: "#ffb700",
    bg: "rgba(255, 183, 0, 0.15)",
    iconName: "compass",
    renderStyle: "classic_neon",
    palette: ["#ffb700", "#7f5c00"],
    glowColor: "rgba(255, 183, 0, 0.6)",
    shadowBlur: "10px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-amber-600 to-yellow-800 text-amber-100 border-amber-400 shadow-[0_0_10px_rgba(255,183,0,0.5)]",
    config3D: {
      meshType: "classicNeonProtractor3d",
      colorMain: "#ffb700",
      colorGlow: "#ffb700",
      colorAccent: "#7f5c00",
      roughness: 0.3,
      metalness: 0.7,
      wireframe: true,
      rotationSpeed: 0.005,
      particleEffect: "none"
    }
  },
  {
    id: "skin_protractor_chronos_time",
    type: "protractor",
    name: "Rapporteur Chronos Time",
    rarity: "Rare",
    price: 220,
    gameRef: "Chrono Trigger",
    desc: "Rapporteur temporel doté d'engrenages néon dorés.",
    color: "#ffd700",
    bg: "rgba(255, 215, 0, 0.2)",
    iconName: "clock",
    renderStyle: "chronos_time",
    palette: ["#ffd700", "#b45309"],
    glowColor: "rgba(255, 215, 0, 0.75)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-yellow-500 via-amber-600 to-amber-900 text-yellow-100 border-yellow-300 shadow-[0_0_12px_rgba(255,215,0,0.6)]",
    config3D: {
      meshType: "chronosDial3d",
      colorMain: "#ffd700",
      colorGlow: "#ffd700",
      colorAccent: "#b45309",
      roughness: 0.2,
      metalness: 0.9,
      wireframe: false,
      rotationSpeed: 0.01,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_protractor_nitro_dial",
    type: "protractor",
    name: "Manomètre Nitro Thruster",
    rarity: "Rare",
    price: 280,
    gameRef: "Motorfest",
    desc: "Rapporteur 180° en forme de cadran de vitesse d'hypercar.",
    color: "#00f0ff",
    bg: "rgba(0, 240, 255, 0.2)",
    iconName: "gauge",
    renderStyle: "vice_speedo",
    palette: ["#00f0ff", "#ef4444"],
    glowColor: "rgba(0, 240, 255, 0.75)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-cyan-600 via-slate-800 to-rose-600 text-cyan-100 border-cyan-400 shadow-[0_0_12px_rgba(0,240,255,0.6)]",
    config3D: {
      meshType: "nitroDial3d",
      colorMain: "#00f0ff",
      colorGlow: "#00f0ff",
      colorAccent: "#ef4444",
      roughness: 0.25,
      metalness: 0.8,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_protractor_dead_island",
    type: "protractor",
    name: "Cadran Sclérotique 180°",
    rarity: "Épique",
    price: 520,
    gameRef: "Dead Island 2",
    desc: "Rapporteur mécanique style lame de scie circulaire graduée.",
    color: "#ff3300",
    bg: "rgba(255, 51, 0, 0.2)",
    iconName: "disc",
    renderStyle: "dead_island",
    palette: ["#ff3300", "#1c1917"],
    glowColor: "rgba(255, 51, 0, 0.8)",
    shadowBlur: "16px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-orange-700 via-stone-900 to-red-700 text-orange-200 border-orange-500 shadow-[0_0_15px_rgba(255,51,0,0.7)]",
    config3D: {
      meshType: "sawProtractor3d",
      colorMain: "#ff3300",
      colorGlow: "#ff3300",
      colorAccent: "#1c1917",
      roughness: 0.5,
      metalness: 0.85,
      wireframe: false,
      rotationSpeed: 0.015,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_protractor_gta_speedo",
    type: "protractor",
    name: "Compteur Vice Sunset",
    rarity: "Légendaire",
    price: 1150,
    gameRef: "GTA VI",
    desc: "Cadran 180° rétro d'hypercar sous le soleil couchant de Vice City.",
    color: "#ff007f",
    bg: "rgba(255, 0, 127, 0.25)",
    iconName: "gauge",
    renderStyle: "vice_speedo",
    palette: ["#ff007f", "#f97316"],
    glowColor: "rgba(255, 0, 127, 0.85)",
    shadowBlur: "20px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-pink-600 via-fuchsia-600 to-orange-500 text-pink-100 border-pink-300 shadow-[0_0_18px_rgba(255,0,127,0.8)]",
    config3D: {
      meshType: "viceSpeedo3d",
      colorMain: "#ff007f",
      colorGlow: "#ff007f",
      colorAccent: "#f97316",
      roughness: 0.2,
      metalness: 0.75,
      wireframe: false,
      rotationSpeed: 0.008,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_protractor_pipboy_radar",
    type: "protractor",
    name: "V.A.T.S. Tactical Dial",
    rarity: "Légendaire",
    price: 1400,
    gameRef: "Fallout",
    desc: "Cadran d'analyse phosphoré vert monochrome avec télémétrie V.A.T.S.",
    color: "#10b981",
    bg: "rgba(16, 185, 129, 0.25)",
    iconName: "compass",
    renderStyle: "vats_radar",
    palette: ["#10b981", "#022c22"],
    glowColor: "rgba(16, 185, 129, 0.9)",
    shadowBlur: "22px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-600 via-green-800 to-black text-emerald-200 border-emerald-400 shadow-[0_0_20px_rgba(16,185,129,0.85)]",
    config3D: {
      meshType: "vatsRadar3d",
      colorMain: "#10b981",
      colorGlow: "#10b981",
      colorAccent: "#022c22",
      roughness: 0.4,
      metalness: 0.2,
      wireframe: true,
      rotationSpeed: 0.005,
      particleEffect: "laserRays"
    }
  },

  // --- FONDS CANVAS ---
  {
    id: "skin_canvas_grid_emerald",
    type: "canvas",
    name: "Grille Émeraude Cyber",
    rarity: "Commune",
    price: 50,
    gameRef: "Matrix",
    desc: "Quadrillage phosphorescent vert émeraude rétro-éclairé.",
    bg: "#04140b",
    grid: "rgba(0, 255, 102, 0.3)",
    iconName: "grid",
    palette: ["#04140b", "#00ff66"],
    glowColor: "rgba(0, 255, 102, 0.5)",
    shadowBlur: "10px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-emerald-800 to-green-950 text-emerald-300 border-emerald-500 shadow-[0_0_10px_rgba(0,255,102,0.4)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#04140b",
      colorGlow: "#00ff66",
      colorAccent: "#00ff66",
      roughness: 0.8,
      metalness: 0.1,
      wireframe: true,
      rotationSpeed: 0.002,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_canvas_synthwave_80s",
    type: "canvas",
    name: "Grille Synthwave 80s",
    rarity: "Rare",
    price: 250,
    gameRef: "Retro Wave",
    desc: "Dégradé violet/magenta avec grille géométrique style Outrun.",
    bg: "#1a0033",
    grid: "rgba(255, 0, 128, 0.4)",
    iconName: "sunset",
    palette: ["#1a0033", "#ff0080"],
    glowColor: "rgba(255, 0, 128, 0.7)",
    shadowBlur: "14px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-purple-800 to-fuchsia-950 text-fuchsia-200 border-fuchsia-400 shadow-[0_0_12px_rgba(255,0,128,0.6)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#1a0033",
      colorGlow: "#ff0080",
      colorAccent: "#ff0080",
      roughness: 0.7,
      metalness: 0.2,
      wireframe: true,
      rotationSpeed: 0.003,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_canvas_cyberpunk_2077",
    type: "canvas",
    name: "Night City Neon Canvas",
    rarity: "Épique",
    price: 600,
    gameRef: "Cyberpunk 2077",
    desc: "Canvas sombre illuminé de néons cyan et jaune haute tension.",
    bg: "#0d0e15",
    grid: "rgba(255, 238, 0, 0.35)",
    iconName: "layout",
    palette: ["#0d0e15", "#ffee00", "#00f0ff"],
    glowColor: "rgba(255, 238, 0, 0.75)",
    shadowBlur: "18px",
    effectType: "glitch",
    badgeClass: "bg-gradient-to-br from-zinc-800 via-amber-600 to-cyan-900 text-yellow-300 border-yellow-400 shadow-[0_0_16px_rgba(255,238,0,0.65)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#0d0e15",
      colorGlow: "#ffee00",
      colorAccent: "#00f0ff",
      roughness: 0.6,
      metalness: 0.4,
      wireframe: true,
      rotationSpeed: 0.004,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_canvas_voxel_biome",
    type: "canvas",
    name: "Voxel Grid Matrix",
    rarity: "Rare",
    price: 300,
    gameRef: "Minecraft",
    desc: "Grille 3D animée en blocs de verre et circuits lumineux.",
    bg: "#091409",
    grid: "rgba(85, 255, 85, 0.35)",
    iconName: "box",
    palette: ["#091409", "#55ff55"],
    glowColor: "rgba(85, 255, 85, 0.65)",
    shadowBlur: "14px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-green-900 to-emerald-950 text-green-300 border-green-500 shadow-[0_0_12px_rgba(85,255,85,0.5)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#091409",
      colorGlow: "#55ff55",
      colorAccent: "#55ff55",
      roughness: 0.8,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.002,
      particleEffect: "none"
    }
  },
  {
    id: "skin_canvas_jurassic_paddock",
    type: "canvas",
    name: "Grille Thermique Paddock",
    rarity: "Épique",
    price: 650,
    gameRef: "Jurassic World",
    desc: "Canvas vert sonar d'enclos avec balayage radar thermique.",
    bg: "#04140b",
    grid: "rgba(0, 255, 102, 0.35)",
    iconName: "activity",
    palette: ["#04140b", "#00ff66"],
    glowColor: "rgba(0, 255, 102, 0.8)",
    shadowBlur: "18px",
    effectType: "scanline",
    badgeClass: "bg-gradient-to-br from-teal-900 via-emerald-800 to-black text-emerald-200 border-teal-400 shadow-[0_0_16px_rgba(0,255,102,0.7)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#04140b",
      colorGlow: "#00ff66",
      colorAccent: "#00ff66",
      roughness: 0.85,
      metalness: 0.15,
      wireframe: true,
      rotationSpeed: 0.003,
      particleEffect: "laserRays"
    }
  },
  {
    id: "skin_canvas_vice_sunset_v2",
    type: "canvas",
    name: "Vice City Neon Grid",
    rarity: "Légendaire",
    price: 1350,
    gameRef: "GTA VI",
    desc: "Dégradé fuchsia/orange rétro-futuriste avec silhouettes.",
    bg: "#1f0529",
    grid: "rgba(255, 0, 128, 0.45)",
    iconName: "sun",
    palette: ["#1f0529", "#ff0080", "#f97316"],
    glowColor: "rgba(255, 0, 128, 0.85)",
    shadowBlur: "22px",
    effectType: "pulse",
    badgeClass: "bg-gradient-to-br from-fuchsia-800 via-pink-700 to-orange-900 text-pink-200 border-pink-400 shadow-[0_0_20px_rgba(255,0,128,0.8)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#1f0529",
      colorGlow: "#ff0080",
      colorAccent: "#f97316",
      roughness: 0.7,
      metalness: 0.3,
      wireframe: true,
      rotationSpeed: 0.003,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_canvas_diablo_sanctuary",
    type: "canvas",
    name: "Dalle Cendrée de Sanctuarium",
    rarity: "Légendaire",
    price: 1500,
    gameRef: "Diablo IV",
    desc: "Sol de donjon en pierre sombre gravé de runes incandescentes.",
    bg: "#140303",
    grid: "rgba(255, 40, 0, 0.4)",
    iconName: "flame",
    palette: ["#140303", "#ff2800"],
    glowColor: "rgba(255, 40, 0, 0.9)",
    shadowBlur: "22px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-red-950 via-rose-950 to-black text-red-300 border-red-600 shadow-[0_0_20px_rgba(255,40,0,0.85)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#140303",
      colorGlow: "#ff2800",
      colorAccent: "#ff2800",
      roughness: 0.9,
      metalness: 0.1,
      wireframe: false,
      rotationSpeed: 0.002,
      particleEffect: "sparks"
    }
  },
  {
    id: "skin_canvas_deep_space_nebula",
    type: "canvas",
    name: "Deep Space Nebula 3D",
    rarity: "Exotique",
    price: 2500,
    gameRef: "Starfield",
    desc: "Fond spatial profond aux poussières d'étoiles et nébuleuses violettes.",
    bg: "#05021a",
    grid: "rgba(147, 51, 234, 0.4)",
    iconName: "sparkles",
    palette: ["#05021a", "#9333ea", "#3b82f6"],
    glowColor: "rgba(147, 51, 234, 0.95)",
    shadowBlur: "28px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-indigo-900 via-purple-900 to-slate-950 text-purple-200 border-indigo-400 shadow-[0_0_25px_rgba(147,51,234,0.9)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#05021a",
      colorGlow: "#9333ea",
      colorAccent: "#3b82f6",
      roughness: 0.95,
      metalness: 0.05,
      wireframe: false,
      rotationSpeed: 0.001,
      particleEffect: "floatingRings"
    }
  },
  {
    id: "skin_canvas_elden_tree",
    type: "canvas",
    name: "Sanctuaire de l'Arbre-Monde",
    rarity: "Exotique",
    price: 3200,
    gameRef: "Elden Ring",
    desc: "Canvas doré émanant des particules de Grâce et des runes ancestrales.",
    bg: "#181003",
    grid: "rgba(251, 191, 36, 0.35)",
    iconName: "sparkles",
    palette: ["#181003", "#fbbf24", "#d97706"],
    glowColor: "rgba(251, 191, 36, 0.85)",
    shadowBlur: "30px",
    effectType: "particles",
    badgeClass: "bg-gradient-to-br from-amber-700 via-yellow-600 to-amber-950 text-amber-100 border-yellow-200 shadow-[0_0_28px_rgba(251,191,36,0.95)]",
    config3D: {
      meshType: "canvasGrid3d",
      colorMain: "#181003",
      colorGlow: "#fbbf24",
      colorAccent: "#d97706",
      roughness: 0.85,
      metalness: 0.4,
      wireframe: false,
      rotationSpeed: 0.002,
      particleEffect: "sparks"
    }
  }
];